#!/bin/bash
#$ -cwd
#$ -V
#$ -l data

# # INTERNAL SCRIPT FOR finding orthologous genes
# $1 - reference organism
# $2 - gene list (to look for orthologous genes)
# $3 - output file for gene list from OrthoDB
# $4 - ANNO_FILE

##ENTRYPOINT

f_org_name=$1
#readarray gene_list < $2
gene_list=($(cat $2 | grep -v -w -i "gene"))
ANNO_FILE=$4

source functions.sh

TEMP_PATH=$(grep -i -w "temp_path" parameters.txt | check_param) 
ORTHODB_PATH_PREFIX=$(grep -i -w "orthodb_path_prefix" parameters.txt | check_param) 
REF_ORGS=$(grep -i -w "ref_orgs" parameters.txt | check_param) 
GENE_SEARCH_MODE=$(grep -i -w "gene_search_mode" parameters.txt | check_param)
n_threads=$(grep -i -w "max_concurrent_jobs" parameters.txt | check_param)

MODE=""
if [[ $GENE_SEARCH_MODE=="HARD" ]]; then
  MODE="-w"
fi

mkdir -p files/genes/$f_org_name/odb/

#Check if ODB files exist
if [[ ( ! -s "$ORTHODB_PATH_PREFIX"_OGgenes_fixed.tab.gz || ! -s "$ORTHODB_PATH_PREFIX"_OGgenes_fixed_user.tab.gz ) && ! -s "$ORTHODB_PATH_PREFIX"_species.tab.gz ]] ; then
  >&2 color_FG_Bold $Red "2. OrthoDB files missing/corrupt"
  >&2 color_FG_Bold $Red "2. Require: "$ORTHODB_PATH_PREFIX"_OGgenes_fixed.tab.gz, "$ORTHODB_PATH_PREFIX"_OGgenes_fixed_user.tab.gz, "$ORTHODB_PATH_PREFIX"_species.tab.gz"
  exit -1
fi

if ! gunzip -t "$ORTHODB_PATH_PREFIX"_OGgenes_fixed_user.tab.gz ; then
  if ! gunzip -t "$ORTHODB_PATH_PREFIX"_OGgenes_fixed.tab.gz ; then
    exit -1
  else
    ODB_FILE="$ORTHODB_PATH_PREFIX"_OGgenes_fixed.tab.gz
    >&1 echo $(color_FG $Yellow "2. Selected Fixed ODB file : ")$(color_FG_BG_Bold $White $BG_Purple "$ODB_FILE")
  fi
  >&2 color_FG_Bold $Red "2. Error in ODB files! Rerun merge_OG2genes_OrthoDB.sh $2"
  exit -1
else
  ODB_FILE="$ORTHODB_PATH_PREFIX"_OGgenes_fixed_user.tab.gz
  >&1 echo $(color_FG $Yellow "2. Selected Fixed ODB (User) file : ")$(color_FG_BG_Bold $White $BG_Purple "$ODB_FILE")
fi

readarray refs < $REF_ORGS

s_names=($(awk  -v s_var='_' '{ gsub(/[[:punct:]]/,s_var);}1' <(echo "${gene_list[@]}")))
genes_strip=($(awk -F'_' '{print $(echo '$1')}' <(echo "${s_names[@]}")))
lookup_genes=($(echo "${genes_strip[@]}" "${gene_list[@]}" | sort | uniq | awk 'NF' ))
org_name=$(echo $f_org_name | awk '{ gsub(/[[:punct:]]/, " ", $0) } 1;')

#Find ODB ORGANISM ID for the organism
org_ID=$(zgrep -i -P "\t\b($org_name)\b\t" "$ORTHODB_PATH_PREFIX"_species.tab.gz | awk '{print $2}')
if [[ -z $org_ID ]] ; then
  org_ID=$(zgrep -i -P "($org_name)" "$ORTHODB_PATH_PREFIX"_species.tab.gz | awk '{print $2}')
fi

if [[ ! -z $org_ID ]] ; then

  #Find ODB ORGANISM ID for the reference organism(s)
  for ref in "${refs[@]}"; do 
    ref_org_name=$(echo $ref | awk '{ gsub(/[[:punct:]]/, " ", $0) } 1;')
    ref_org_ID=""
    ref_org_ID=$(zgrep -i -P "\t\b($ref_org_name)\b\t" "$ORTHODB_PATH_PREFIX"_species.tab.gz | awk '{print $2}')
    if [[ -z $ref_org_ID ]] ; then
      ref_org_ID=$(zgrep -i -P "($ref_org_name)" "$ORTHODB_PATH_PREFIX"_species.tab.gz | awk '{print $2}')
    fi
    if [[ ! -z $ref_org_ID && $ref_org_ID != $f_org_name ]] ; then
      ref_org_IDs+=($ref_org_ID)
    fi
  done

#Get only the ODB GENE IDs, genes and ODB clusters of the reference organisms from the reduced ODB FILE which is generated by merge_OG2genes_OrthoDB.sh
zgrep -f <(printf -- '%s\n' "${ref_org_IDs[@]}") $ODB_FILE | gzip -c > $TEMP_PATH/$f_org_name/odb.clusters.gz

#ODB GENE IDs and GENE NAMES are delimited with || which I am splitting with awk regexp \|/|, and selecting the elements which match the organisms and genes
zcat -f $TEMP_PATH/$f_org_name/odb.clusters.gz | awk '{print $2}' | sed 's/,/\n/g' | grep -w "$org_ID" - | grep -i $MODE -f <(printf -- '%s\n' "${lookup_genes[@]}") - | awk '{split($0,a,/\|\|/); print a[2]}' | sort -u > $3

>&1 echo $(color_FG $Green "2. DONE: Found Orthologous genes : ")$(color_FG_BG_Bold $White $BG_Purple "$3")

#Save selected clusters and the participating genes(delimiter=",") in odb.final_map
zgrep "$org_ID" $TEMP_PATH/$f_org_name/odb.clusters.gz | awk '{split($3,a,","); for(key in a){print $1"\t"a[key]}}' | grep -i $MODE -f <(cat $2 $3 | grep -v -w -i "gene") | sort -u | awk '{if($1 in a){a[$1]=a[$1]","$2}else{a[$1]=$2;} } END{for(key in a){print key"\t"a[key]}}' > files/genes/$f_org_name/odb.final_map

>&1 echo $(color_FG $Green "2. DONE: Mapped gene names to clusters : ")$(color_FG_BG_Bold $White $BG_Purple "files/genes/$f_org_name/odb.final_map")

rm -f $TEMP_PATH/$f_org_name/odb.clusters.gz

else
  >&2 color_FG_Bold $Red "2. $org_name not found in OrthoDB files"
fi

exit 0